# Generated by Django 5.0.3 on 2024-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_created_at_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
